name: smart_reminder_app
description: A simple reminder app with notification and countdown

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

flutter:
  uses-material-design: true

  assets:
  # Add this if you have any icons or images
  # - assets/images/
